### ISSUE TITLE
Please add assembly support

### ISSUE THREAD

**Issue by sergio-faraldo** [CMGSK/MikuMikuBot#1]

**Comment by sergio-faraldo** [comment]
![image](https://github.com/user-attachments/assets/88dc3654-52ff-4ea7-abc0-1a638154a117)

**Comment by CMGSK** [comment]
@sergio-faraldo 

[e](https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee)
